server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_db?createDatabaseIfNotExist=true
    username: root
    password: Root@1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 9371361939-80k7fidc68nnndpvpgsfshcd99h37qku.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth2/callback

            scope:
              - email
              - profile

#Security
# If you used '-' in secret then we should need to encode base64
jwt:
  secret: software-architecture-jwt-secret
  #jwt.secret=softwarelaskjgldjglsdjglsjdlhjdflhjdflhjlkdfjh
  # Expired in 15 min
  token:
    expire-seconds: 900000

  #  http:
#    multipart:
#      max-file-size: 500MB
#      max-request-size: 500MB
#  http:
#    multipart:
#      enabled: true
#      max-file-size: 5000MB
#      max-request-size: 5000MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB

file:
  upload-directory: classpath:/static/



